sudo: false
language: ruby
rvm: 2.1.9
addons:
  apt:
    packages:
    - yajl-tools
install:
  - git clone --depth 1 -b local git://github.com/theforeman/jenkins-job-builder.git
  - (cd jenkins-job-builder && pip install --user -r requirements.txt && pip install --user .)
  - (cd puppet && bundle install)
script: ./.travis.sh
